[package]
name = "do-rs"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
execute = "0.2.13"
serde_json = "1.0.114"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
